services:
  graph_database:
    container_name: graph_database
    image: kemele/virtuoso:7-stable
    restart: unless-stopped
    ports:
      - "8890:8890"
    volumes:
      - graph_data:/.data

  sparql_ui:
    container_name: sparql_ui
    image: erikap/yasgui:latest
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      - ENABLE_ENDPOINT_SELECTOR=true
      - DEFAULT_SPARQL_ENDPOINT=http://localhost:8890/sparql

  graph_visualizer:
    container_name: graph_visualizer
    image: node:lts-alpine
    restart: unless-stopped
    ports:
      - "19006:19006"
    working_dir: /app
    environment:
      - HOST=0.0.0.0
    command: >
      sh -c "apk add --no-cache git &&
             rm -rf ./* .git &&
             git clone https://github.com/MaastrichtU-IDS/into-the-graph.git . &&
             yarn install &&
             yarn build &&
             yarn global add serve &&
             serve -s web-build -l 5000"

volumes:
  graph_data:
