services:
  # --- VIRTUOSO STACK ---
  graph_database:
    container_name: graph_database
    image: kemele/virtuoso:7-stable
    restart: unless-stopped
    profiles: ["virtuoso", "all"]
    ports:
      - "8890:8890"
    volumes:
      - graph_data:/.data

  sparql_ui:
    container_name: sparql_ui
    image: erikap/yasgui:latest
    restart: unless-stopped
    profiles: ["virtuoso", "all"]
    ports:
      - "8080:80"
    environment:
      - ENABLE_ENDPOINT_SELECTOR=true
      - DEFAULT_SPARQL_ENDPOINT=http://localhost:8890/sparql

  # --- GRAPHDB STACK ---
  graphdb:
    container_name: graphdb
    image: ontotext/graphdb:10.7.0
    restart: unless-stopped
    profiles: ["graphdb", "all"]
    ports:
      - "7200:7200"
    volumes:
      - graphdb_data:/opt/graphdb/home

volumes:
  graph_data:
  graphdb_data: