"""Generates synthetic Knowledge Graphs using extensional data and Horn rules.

This module provides the core pipeline for triple generation, applying a set of graph
metrics and logical rules to produce a complete, synthetic N-Triples dataset.
"""

import copy
import itertools
import logging
import random
from collections.abc import Iterator
from pathlib import Path
from typing import Any, NamedTuple, TypedDict

from SPARQLWrapper import SPARQLWrapper

from graph_metrics import PredicateProfile
from queries import (
    SparqlBinding,
    build_filtered_query,
    build_rule_query,
    clear_graph_sparql,
    count_triples,
    execute_ask_query,
    execute_select_query,
    from_binding_row,
    insert_triples_gsp,
    insert_triples_sparql,
)
from rules import Atom, HornRule, RuleSignature, get_extensional_dependencies
from utils import format_term, format_triple

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Raw Triple.
# ---------------------------------------------------------------------------
class RawTriple(NamedTuple):
    """Represents an extracted, unformatted triple."""

    predicate: str
    subject_val: str
    object_val: str
    object_type: str


# ---------------------------------------------------------------------------
# Profile update.
# ---------------------------------------------------------------------------
def decrement_counts(counts: dict[str, int], term: str) -> None:
    """Module-level private helper for managing frequency state."""
    if term in counts:
        counts[term] -= 1
        if counts[term] == 0:
            del counts[term]
    else:
        logger.warning(
            "Decrementing the count of %s when it does not exist in counter", term
        )


def update_closed_preds(
    edb_profiles: dict[str, PredicateProfile],
    closed_preds: set[str],
) -> bool:
    """Module-level private helpter to update the state of the predicates. Returns True
    if new predicates are closed."""
    new = False
    for predicate, profile in edb_profiles.items():
        if profile.frequency <= 0 and predicate not in closed_preds:
            closed_preds.add(predicate)
            new = True

    return new


# ---------------------------------------------------------------------------
# EDB Generation
# ---------------------------------------------------------------------------
def random_triples(
    profile: PredicateProfile, predicate: str, term_mapping: dict[str, str]
) -> Iterator[str]:
    """Yield random triples generated by assigning random objects to a fixed subject."""
    subject = random.choice(list(profile.domain.keys()))
    subject_str = format_term(subject, term_mapping)
    required_count = profile.domain[subject_str]
    available_objects = list(profile.range.keys() - {subject_str})

    if len(available_objects) < required_count:
        raise ValueError(f"Error: Ran out of objects for '{predicate}'")

    chosen_objects = random.sample(available_objects, required_count)

    for obj in chosen_objects:
        yield format_triple(subject, predicate, obj, term_mapping)
        obj_str = format_term(obj, term_mapping)
        decrement_counts(profile.range, obj_str)
        profile.frequency -= 1

    del profile.domain[subject]


def insert_random_triples(
    client: SPARQLWrapper,
    edb_uri: str,
    profile: PredicateProfile,
    predicate: str,
    term_mapping: dict[str, str],
    chunk_size: int,
):
    triple_stream = random_triples(
        profile=profile, predicate=predicate, term_mapping=term_mapping
    )
    return insert_triples_sparql(
        client=client,
        graph_uri=edb_uri,
        triple_stream=triple_stream,
        chunk_size=chunk_size,
    )


def filter_bindings(
    client: SPARQLWrapper,
    edb_uri: str,
    intensional_preds: set[str],
    raw_bindings: list[SparqlBinding],
    searchspace_profiles: dict[str, PredicateProfile],
    rule: HornRule,
    term_mapping: dict[str, str],
    closed_preds: set[str],
) -> Iterator[str]:
    """Yields triples for EDB generation while checking if the triple is allowed by
    predicate metrics."""

    kwargs = {"client": client, "edb_uri": edb_uri, "term_mapping": term_mapping}

    # If the rule only has extensional rules in its body, we must satisfy rule's support
    support = rule.support
    only_extensional = True
    excluded_preds = intensional_preds.union(closed_preds)
    if any(p in excluded_preds for p in rule.get_body_predicates()):
        only_extensional = False

    if only_extensional and (_count := len(raw_bindings)) < support:
        m = f"{rule.rule_id}'s support is {support} but only {_count} bindings found."
        raise ValueError(m)

    # Shuffle the bindings
    candidate_bindings = list(raw_bindings)
    random.shuffle(candidate_bindings)

    selected_bindings = select_valid_bindings(
        **kwargs,
        bindings=candidate_bindings,
        rule=rule,
        searchspace_profiles=copy.deepcopy(searchspace_profiles),
    )

    if len(selected_bindings) < rule.support and only_extensional:
        logger.warning(
            "%s's support is %d, but %d bindings were retrieved.",
            rule.rule_id,
            rule.support,
            len(selected_bindings),
        )

    # Produce the new triples from selected bindings
    for idx in selected_bindings:
        binding_row = candidate_bindings[idx]
        for atom in (a for a in rule.body if a.predicate in searchspace_profiles):
            predicate = atom.predicate
            subject, _ = from_binding_row(atom.subject, binding_row)
            subject_str = format_term(subject)
            obj, _ = from_binding_row(atom.obj, binding_row)
            obj_str = format_term(obj)

            triple = format_triple(
                subject=subject,
                predicate=predicate,
                obj=obj,
                term_mapping=term_mapping,
            )

            decrement_counts(searchspace_profiles[predicate].domain, subject_str)
            decrement_counts(searchspace_profiles[predicate].range, obj_str)
            searchspace_profiles[predicate].frequency -= 1
            yield triple


def select_valid_bindings(
    client: SPARQLWrapper,
    edb_uri: str,
    bindings: list[SparqlBinding],
    rule: HornRule,
    searchspace_profiles: dict[str, PredicateProfile],
    term_mapping: dict[str, str],
) -> list[int]:
    """Selects a set of valid bindings."""
    added_bindings: list[int] = []  # List of idx of added bindings
    added_triples = []  # TODO (optim): This is not efficient memory-wise

    for row_idx, binding_row in enumerate(bindings):
        if len(added_bindings) >= rule.support:
            break

        add_current_binding = True
        for atom in (a for a in rule.body if a.predicate in searchspace_profiles):
            # Extract triple from bindings
            predicate = atom.predicate
            subject, _ = from_binding_row(atom.subject, binding_row)
            obj, _ = from_binding_row(atom.obj, binding_row)

            # Parse triple
            subject_str = format_term(subject, term_mapping)
            obj_str = format_term(obj, term_mapping)
            triple = format_triple(
                subject=subject_str,
                predicate=obj_str,
                obj=obj,
                term_mapping=term_mapping,
            )

            # If this triple exists in the graph there is no need for checking metrics
            query = f"ASK {{ GRAPH <{edb_uri}> {{ {triple} }} }}"
            if triple in added_triples or execute_ask_query(client, query):
                continue

            # Check if the frequency of the predicate is already met.
            if not searchspace_profiles[predicate].frequency:
                add_current_binding = False
                break

            # Check if domain or range of the predicate are already met.
            if subject_str not in searchspace_profiles[predicate].domain:
                add_current_binding = False
                break
            if obj_str not in searchspace_profiles[predicate].range:
                add_current_binding = False
                break

            # Check if adding this triples makes non-duplicates impossible
            aux_profile = copy.deepcopy(searchspace_profiles[predicate])
            decrement_counts(aux_profile.domain, subject_str)
            decrement_counts(aux_profile.range, obj_str)
            aux_profile.frequency -= 1

            if max(aux_profile.domain.values(), default=0) > len(
                aux_profile.range
            ) or max(aux_profile.range.values(), default=0) > len(aux_profile.domain):
                add_current_binding = False
                break

            # If we select this binding, this triple must be produced
            added_triples.append(triple)

            # Update the proxy profile
            decrement_counts(searchspace_profiles[predicate].domain, subject_str)
            decrement_counts(searchspace_profiles[predicate].range, obj_str)
            searchspace_profiles[predicate].frequency -= 1

        if add_current_binding:
            added_bindings.append(row_idx)

    return added_bindings


def check_direct_matches(
    client: SPARQLWrapper,
    edb_uri: str,
    profiles: dict[str, PredicateProfile],
    term_mapping: dict[str, str],
    chunk_size: int,
) -> int:
    """Retrieves the triples that must be added to the EDB from a set of rules and
    profiles and inserts them into the EDB.

    Returns the number of triples inserted to the EDB."""

    def direct_triples(
        profiles: dict[str, PredicateProfile], term_mapping: dict[str, str]
    ) -> Iterator[str]:
        """Yields triples that must be added to the EDB."""
        while True:
            progress_made = False

            for predicate, profile in profiles.items():
                # Check for direct matches on domain
                for subject, frequency in list(profile.domain.items()):
                    obj_choices = list(profile.range.keys() - {subject})
                    if frequency == len(obj_choices):
                        for obj in obj_choices:
                            yield format_triple(subject, predicate, obj, term_mapping)
                            obj_str = format_term(obj)
                            decrement_counts(profile.range, obj_str)
                            profile.frequency -= 1
                        del profile.domain[subject]
                        progress_made = True

                # Check for direct matches on range
                for obj, frequency in list(profile.range.items()):
                    subj_choices = list(profile.domain.keys() - {obj})
                    if frequency == len(subj_choices):
                        for subject in subj_choices:
                            yield format_triple(subject, predicate, obj, term_mapping)
                            subj_str = format_term(subject, term_mapping)
                            decrement_counts(profile.domain, subj_str)
                            profile.frequency -= 1
                        del profile.range[obj]
                        progress_made = True

            if not progress_made:
                break

    triples = direct_triples(profiles=profiles, term_mapping=term_mapping)
    return insert_triples_sparql(
        client=client,
        graph_uri=edb_uri,
        triple_stream=triples,
        chunk_size=chunk_size,
    )


def check_triples_from_rule(
    rule: HornRule,
    intensional_preds: set[str],
    closed_preds: set[str],
    edb_profiles: dict[str, PredicateProfile],
    client: SPARQLWrapper,
    term_mapping: dict[str, str],
    edb_uri: str,
    chunk_size: int,
) -> int:
    """Retrieves triples that satisfy a rule's body and inserts them into the EDB."""
    # Create a new rule without head and without intensional predicates
    new_body = frozenset(
        {atom for atom in rule.body if atom.predicate not in intensional_preds}
    )

    new_rule = HornRule(
        signature=RuleSignature(
            rule_id=rule.rule_id,
            body=frozenset({a for a in new_body if a.predicate not in closed_preds}),
            head=Atom("", "", ""),
        ),
        support=rule.support,
        head_coverage=rule.head_coverage,
        std_confidence=rule.std_confidence,
        pca_confidence=rule.pca_confidence,
        classification=rule.classification,
    )

    # Create the searchspace
    searchspace_profiles: dict[str, PredicateProfile] = {}
    for predicate, profile in edb_profiles.items():
        if predicate in (new_rule.get_body_predicates()):
            searchspace_profiles[predicate] = profile

    searchspace_uri = "http://SearchSpace.org/"
    clear_graph_sparql(client=client, graph_uri=searchspace_uri)
    create_searchspace(
        client=client,
        profiles=searchspace_profiles,
        term_mapping=term_mapping,
        searchspace_uri=searchspace_uri,
    )

    # Query the searchspace
    sources = GraphSources(target=searchspace_uri, others=[])
    query = build_rule_query(rule=new_rule.signature, sources=sources)
    bindings = execute_select_query(client, query)

    # Filter the retrieved bindings
    triple_stream = filter_bindings(
        client=client,
        edb_uri=edb_uri,
        rule=rule,
        raw_bindings=bindings,
        term_mapping=term_mapping,
        searchspace_profiles=searchspace_profiles,
        intensional_preds=intensional_preds,
        closed_preds=closed_preds,
    )
    return insert_triples_sparql(
        client=client,
        graph_uri=edb_uri,
        triple_stream=triple_stream,
        chunk_size=chunk_size,
    )


def create_extensional_graph(
    client: SPARQLWrapper,
    rules: dict[str, HornRule],
    profiles: dict[str, PredicateProfile],
    edb_uri: str,
    term_mapping: dict[str, str],
    chunk_size: int = 1000,
) -> None:
    """Creates an EDB from a set of profiles and rules."""
    intensional_preds = {r.head.predicate for r in rules.values()}
    extensional_preds = profiles.keys() - intensional_preds

    rule_dependency = get_extensional_dependencies(rules)

    relevant_rules: dict[str, HornRule] = {}
    for r_id, r in rules.items():
        if any(pred not in intensional_preds for pred in r.get_predicates()):
            relevant_rules[r_id] = r

    edb_profiles: dict[str, PredicateProfile] = {}
    for predicate, profile in profiles.items():
        if predicate in extensional_preds:
            edb_profiles[predicate] = profile

    clear_graph_sparql(client=client, graph_uri=edb_uri)
    logger.info("Cleared <%s>.", edb_uri)

    checked_rules = set()
    closed_preds = set()

    kwargs = {
        "client": client,
        "edb_uri": edb_uri,
        "term_mapping": term_mapping,
        "chunk_size": chunk_size,
    }

    logger.info("Generating EDB...")
    step = 0
    while True:
        step += 1
        progress = False

        # Step 1: Check direct matches
        if d_count := check_direct_matches(**kwargs, profiles=edb_profiles):
            progress = True
            logger.debug("[Step %d]: Added %d triples directly.", step, d_count)

            if update_closed_preds(edb_profiles, closed_preds):
                closed = len(closed_preds)
                n_open = len(edb_profiles) - closed
                logger.info(
                    "[Step %d]: Closed [%d/%d].", step, closed, len(edb_profiles)
                )

                if not n_open:
                    logger.info("All ext. predicates closed.")
                    break

        # Step 2: Check rule bodies
        for r_id, r in relevant_rules.items():
            if r_id in checked_rules:
                continue
            if rule_dependency[r_id] - checked_rules:
                continue
            if (r.get_predicates() - intensional_preds) - closed_preds:
                # Use this rule
                r_count = check_triples_from_rule(
                    **kwargs,
                    rule=r,
                    intensional_preds=intensional_preds,
                    closed_preds=closed_preds,
                    edb_profiles=edb_profiles,
                )
                checked_rules.add(r_id)
                progress = True

                if r_count:
                    logger.debug(
                        "[Step %d]: Adding %d triples from %s",
                        step,
                        r_count,
                        r.rule_id,
                    )
                    if update_closed_preds(edb_profiles, closed_preds):
                        closed = len(closed_preds)
                        n_open = len(edb_profiles) - closed
                        logger.info(
                            "[Step %d]: Closed ext. predicactes: [%d/%d].",
                            step,
                            closed,
                            len(edb_profiles),
                        )

                        if not n_open:
                            logger.info("All ext. predicates closed.")
                            break
                break

        # # Step 3: Assign randomly
        if not progress:
            predicate = random.sample(edb_profiles.keys() - closed_preds, 1)[0]
            profile = edb_profiles[predicate]

            ran_count = insert_random_triples(
                **kwargs,
                predicate=predicate,
                profile=profile,
            )
            logger.debug(
                "[Step %d]: Added %d triples by random assignment.", step, ran_count
            )

            if ran_count:
                if update_closed_preds(edb_profiles, closed_preds):
                    closed = len(closed_preds)
                    n_open = len(edb_profiles) - closed
                    logger.info(
                        "[Step %d]: Closed ext. predicactes: [%d/%d].",
                        step,
                        closed,
                        len(edb_profiles),
                    )

                    if not n_open:
                        logger.info("All ext. predicates closed.")
                        break


def run_edb_generation_experiment(config_file: Path):
    import time

    import pandas as pd
    from SPARQLWrapper import DIGEST

    from config import RunConfig
    from graph_metrics import GraphMetrics
    from rules import check_uninferrable_preds, get_term_mapping, parse_rule_set
    from utils import setup_logging

    ## ------ Setup ------
    config = RunConfig.from_json(config_file)
    setup_logging(level=config.logging.level)
    logger.info("Confifuration correctly initialized.")

    input_dir = config.data.input_dir
    rules_file = input_dir / config.rules.rules_file
    graph_uri = config.graph.base_graph_uri

    logger.debug("BASE GRAPH URI: <%s>", graph_uri)

    client = SPARQLWrapper(str(config.data.database_url / config.data.sparql_endpoint))
    client.setHTTPAuth(DIGEST)
    client.setCredentials(config.virtuoso.user, config.virtuoso.password)

    graph_metrics = GraphMetrics.from_uri(client, graph_uri)

    ## ------ Previous evaluation of rules and Graph Metrics ------
    rule_dataframe = pd.read_csv(rules_file)

    term_mapping = get_term_mapping(
        input_dir / config.graph.ontology_file, default_namespace=graph_uri
    )

    rules = parse_rule_set(
        rule_dataframe=rule_dataframe,
        term_mapping=term_mapping,
        pca_threshold=config.rules.pca_threshold,
    )

    intensional_predicates = {rule.head.predicate for rule in rules.values()}
    extensional_predicates = graph_metrics.profiles.keys() - intensional_predicates

    logger.debug(
        "\nExtensional predicates:\n\t%s\nIntensional predicates:\n\t%s",
        extensional_predicates,
        intensional_predicates,
    )

    if uninferrable_preds := check_uninferrable_preds(
        rules=rules,
        intensional_predicates=intensional_predicates,
        extensional_predicates=extensional_predicates,
    ):
        error_msg = (
            f"Rule set not inferrable under complete rule assumption. "
            f"The following predicates cannot be deduced: {uninferrable_preds}."
        )
        logger.error(error_msg)
        raise RuntimeError(error_msg)

    ## ------ Extensional Graph Generation  ------
    profiles = graph_metrics.profiles
    edb_profiles = {k: profiles[k] for k in extensional_predicates}

    start_time = time.time()

    edb_uri = graph_uri.replace(".org", "EDB.org")
    create_extensional_graph(
        client=client,
        rules=rules,
        profiles=edb_profiles,
        edb_uri=edb_uri,
        term_mapping=term_mapping,
        chunk_size=config.virtuoso.chunk_size,
    )

    logger.info("Execution finished after %d s.", time.time() - start_time)
    logger.info(
        "EDB at <%s> has %d triples.",
        edb_uri,
        count_triples(client=client, graph_uri=edb_uri),
    )


# -----------------------------------------------------------------------------
# Create searchspace.
# ---------------------------------------------------------------------------
def create_searchspace(
    client: SPARQLWrapper,
    profiles: dict[str, PredicateProfile],
    term_mapping: dict[str, str],
    searchspace_uri: str,
) -> None:
    """Generates and inserts a searchspace into the DB using one or more predicates.

    Creates all possible triples for the given predicate using the cartesian
    product of the domain and range entities, and inserts them into a specific
    named graph using batching to ensure scalability.

    Args:
        database_endpoint: The URL of the SPARQL database endpoint.
        predicate: The URI of the predicate to link subjects and objects.
        profile: A profile object containing `domain` and `range` Counters.

    Returns:
        The URI of the generated search space named graph.

    Raises:
        Exception: If a SPARQL insertion batch fails.
    """
    logger.debug("Creating searchspace for %s", list(profiles.keys()))

    for predicate, profile in profiles.items():
        triple_generator: Iterator[str] = (
            format_triple(subj, predicate, obj, term_mapping)
            for subj, obj in itertools.product(
                profile.domain.keys(), profile.range.keys()
            )
        )
        insert_triples_gsp(
            graph_uri=searchspace_uri,
            triples=triple_generator,
            client=client,
        )


# ---------------------------------------------------------------------------
# Apply rules.
# ---------------------------------------------------------------------------
class GraphSources(TypedDict):
    target: str
    others: list[str]


def apply_rule(
    client: SPARQLWrapper,
    graph_uri: str,
    rule: HornRule,
    use_head: bool,
    term_mapping: dict[str, str],
    chunk_size: int,
    profile: PredicateProfile | None = None,
) -> int:
    """Generates and inserts triples to 'graph_uri'.

    Args:
        client: SPARQLWrapper client.
        graph_uri: URI of the graph where data is queried and inserted.
        rule: Rule represented as a Horn Rule.
        profiles: Dict mapping each predicate to its metrics as a PredicateProfile.
        use_head: If True will use rule's head to form the query when recursive.
        chunk_size: Maximum number of triples to insert per SPARQL query.
        term_mapping: Mapping from a term to its corresponding prefix.
    Returns:
        The number of inserted triples.
    """

    predicate = rule.head.predicate
    graph_sources: GraphSources = {
        "target": graph_uri,
        "others": [],
    }

    if profile is not None and predicate in rule.get_body_predicates():
        searchspace_uri = "http://SearchSpace.org/"
        graph_sources["others"].append(searchspace_uri)

        create_searchspace(
            client=client,
            profiles={predicate: profile},
            searchspace_uri=searchspace_uri,
            term_mapping=term_mapping,
        )

    filtered_query, ask_query = build_filtered_query(
        rule=rule.signature,
        sources=graph_sources,
        use_head=use_head,
    )

    if not execute_ask_query(client, ask_query):
        logger.debug("%s does not produce new triples.", rule.rule_id)
        return 0

    raw_bindings = execute_select_query(client, filtered_query)
    if not raw_bindings:
        logger.warning("%s produces new triples, but no bindings found.", rule.rule_id)
        return 0

    triple_iterator = filter_and_format_triples(
        raw_bindings=raw_bindings,
        profile=profile,
        rule=rule,
        term_mapping=term_mapping,
    )

    count = insert_triples_sparql(
        graph_uri=graph_uri,
        client=client,
        triple_stream=triple_iterator,
        chunk_size=chunk_size,
    )

    if not count:
        logger.warning("Found bindings for %s, but still count is 0.", rule.rule_id)
        return 0

    logger.info("%s added %d triples for %s.", rule.rule_id, count, predicate)
    return count


def apply_rules(
    client: SPARQLWrapper,
    graph_uri: str,
    rules: dict[str, HornRule],
    use_head: bool,
    term_mapping: dict[str, str],
    chunk_size: int,
    profiles: dict[str, PredicateProfile] | None = None,
) -> dict[str, HornRule]:
    """Applies each rule once only if it will produce new triples in 'graph_uri'.

    Args:
        client: SPARQLWrapper client.
        graph_uri: URI of the graph that is queried for the rules.
        rules: Dict mapping each rule id to its represnetation as a Horn Rule.
        profiles: Dict mapping each predicate to its metrics as a PredicateProfile.
        use_head: If True will use rule's head to form the query when recursive.
        chunk_size: Maximum number of triples to insert per SPARQL query.
        term_mapping: Mapping from a term to its corresponding prefix.

    Returns:
        A dict with the rules that were applied, excludes the rules that do not produce
        new triples in the graph_uri, thus not applied.
    """
    applied_rules: dict[str, HornRule] = {}
    logger.debug("Applying %d rules.", len(rules))

    for rule_id, rule in rules.items():
        predicate = rule.head.predicate
        profile = profiles.get(predicate) if profiles else None

        count = apply_rule(
            client=client,
            graph_uri=graph_uri,
            rule=rule,
            use_head=use_head,
            term_mapping=term_mapping,
            chunk_size=chunk_size,
            profile=profile,
        )

        if count:
            applied_rules[rule_id] = rule

    return applied_rules


def _is_novel_atom(index: int, binding_row: SparqlBinding) -> bool:
    """Evaluates a boolean flag to check if an atom is novel."""
    is_new_flag = binding_row.get(f"is_new_{index}", {}).get("value", "true")
    return str(is_new_flag).lower() not in ("0", "false")


def _extract_raw_triple(atom: Atom, bindings_row: dict[str, Any]) -> RawTriple | None:
    """Extracts subject and object from bindings to form a complete RawTriple."""
    subject_val, _ = from_binding_row(atom.subject, bindings_row)
    object_val, object_type = from_binding_row(atom.obj, bindings_row)

    if not subject_val or not object_val:
        return None

    return RawTriple(atom.predicate, subject_val, object_val, object_type)


def filter_and_format_triples(
    raw_bindings: list[SparqlBinding],
    profile: PredicateProfile | None,
    rule: HornRule,
    term_mapping: dict[str, str],
) -> Iterator[str]:
    """Filters raw triples against profile constraints and yields RDF strings."""
    h_predicate = rule.head.predicate

    # Shuffle to avoid deterministic bias if multiple valid options exist
    shuffled_bindings = list(raw_bindings)
    random.shuffle(shuffled_bindings)

    # Establish the same target atoms and ordering as the query builder
    target_atoms = sorted([a for a in rule.signature if a.predicate == h_predicate])

    created = 0

    for bindings_row in shuffled_bindings:
        if profile is not None and created >= profile.frequency:
            logger.debug("%s is closed, can't add more triples.", h_predicate)
            break

        triples: set[RawTriple] = set()

        for i, atom in enumerate(target_atoms):
            if not _is_novel_atom(i, bindings_row):
                continue

            if raw_triple := _extract_raw_triple(atom, bindings_row):
                # TODO: If we were to filter the triples, this must be done here
                triples.add(raw_triple)

            else:
                message = f"Missing bindings for {atom} in rule {rule.rule_id}. "
                logger.warning(message)
                continue

        for t in triples:
            if profile is not None and created >= profile.frequency:
                logger.info("%s is closed, can't add more triples.", h_predicate)
                break

            # TODO: This does not take into account possible literals
            if formatted_triple := format_triple(
                subject=t.subject_val,
                predicate=t.predicate,
                obj=t.object_val,
                term_mapping=term_mapping,
            ):
                yield formatted_triple
                created += 1
                # TODO: Update global state


if __name__ == "__main__":
    simpsons_config = Path("configurations/SyntheticGraphGeneration/simpsons.json")
    fr_config = Path(
        "configurations/SyntheticGraphGeneration/french_royalty_std=1.json"
    )
    run_edb_generation_experiment(fr_config)
